const venueDanceMap = [
{ id: "140", daytaught: "Wednesday" },
{ id: "139", daytaught: "Wednesday" },
{ id: "138", daytaught: "Wednesday" },
{ id: "137", daytaught: "Wednesday" },
{ id: "136", daytaught: "Wednesday" },
{ id: "135", daytaught: "Wednesday" },
{ id: "134", daytaught: "Wednesday" },
{ id: "133", daytaught: "Wednesday" },
{ id: "132", daytaught: "Wednesday" },
{ id: "131", daytaught: "Wednesday" },
{ id: "130", daytaught: "Wednesday" },
{ id: "129", daytaught: "Wednesday" },
{ id: "128", daytaught: "Wednesday" },
{ id: "127", daytaught: "Wednesday" },
{ id: "126", daytaught: "Wednesday" },
{ id: "125", daytaught: "Wednesday" },
{ id: "124", daytaught: "Wednesday" },
{ id: "123", daytaught: "Wednesday" },
{ id: "122", daytaught: "Wednesday" },
{ id: "121", daytaught: "Wednesday" },
{ id: "120", daytaught: "Wednesday" },
{ id: "119", daytaught: "Wednesday" },
{ id: "118", daytaught: "Wednesday" },
{ id: "117", daytaught: "Wednesday" },
{ id: "116", daytaught: "Wednesday" },
{ id: "115", daytaught: "Wednesday" },
{ id: "114", daytaught: "Wednesday" },
{ id: "113", daytaught: "Wednesday" },
{ id: "112", daytaught: "Wednesday" },
{ id: "111", daytaught: "Wednesday" },
{ id: "110", daytaught: "Wednesday" },
{ id: "109", daytaught: "Wednesday" },
{ id: "108", daytaught: "Wednesday" },
{ id: "107", daytaught: "Wednesday" },
{ id: "106", daytaught: "Wednesday" },
{ id: "105", daytaught: "Wednesday" },
{ id: "104", daytaught: "Wednesday" },
{ id: "103", daytaught: "Wednesday" },
{ id: "102", daytaught: "Wednesday" },
{ id: "101", daytaught: "Wednesday" },
{ id: "100", daytaught: "Wednesday" },

];

export { venueDanceMap };



