const venueDanceMap = [
{ id: "144", playlist: "Been By Now", daytaught: "Wednesday" },
{ id: "143", playlist: "Capital H", daytaught: "Wednesday" },
{ id: "142", playlist: "Walk on the Beach", daytaught: "Wednesday" },
{ id: "141", playlist: "A Rattlesnake Kiss", daytaught: "Wednesday" },
{ id: "140", playlist: "Boots Off", daytaught: "Wednesday" },
{ id: "139", playlist: "Backup Plan", daytaught: "Wednesday" },
{ id: "138", playlist: "Dance With You", daytaught: "Wednesday" },
{ id: "137", playlist: "Heart of Stone", daytaught: "Wednesday" },
{ id: "136", playlist: "Blame Texas", daytaught: "Wednesday" },
{ id: "135", playlist: "Wish you Well", daytaught: "Wednesday" },
{ id: "134", playlist: "Single Again", daytaught: "Wednesday" },
{ id: "133", playlist: "Something Bout the Summer", daytaught: "Wednesday" },
{ id: "132", playlist: "A Country Song Came On", daytaught: "Wednesday" },
{ id: "131", playlist: "Weren t for the Wind", daytaught: "Wednesday" },
{ id: "130", playlist: "After Party", daytaught: "Wednesday" },
{ id: "129", playlist: "Brown Eyed 5 5", daytaught: "Wednesday" },
{ id: "128", playlist: "Like It Like That", daytaught: "Wednesday" },
{ id: "127", playlist: "Alligator Smile", daytaught: "Wednesday" },
{ id: "126", playlist: "Choosin Texas", daytaught: "Wednesday" },
{ id: "125", playlist: "Do Si Dough", daytaught: "Wednesday" },
{ id: "124", playlist: "Country Tightrope", daytaught: "Wednesday" },
{ id: "123", playlist: "Getaway Car", daytaught: "Wednesday" },
{ id: "122", playlist: "Good Times and Tan Lines", daytaught: "Wednesday" },
{ id: "121", playlist: "Dolly Would", daytaught: "Wednesday" },
{ id: "120", playlist: "Old Ropers", daytaught: "Wednesday" },
{ id: "119", playlist: "Twenty Two", daytaught: "Wednesday" },
{ id: "118", playlist: "Memory Lane-No Teach", daytaught: "Wednesday" },
{ id: "117", playlist: "Happen to Me", daytaught: "Wednesday" },
{ id: "116", playlist: "Baby I Wanna Know", daytaught: "Wednesday" },
{ id: "115", playlist: "Two of Us(no teach/demo)", daytaught: "Wednesday" },
{ id: "114", playlist: "Gin & Tonic Kisses", daytaught: "Wednesday" },
{ id: "113", playlist: "Where the Wild Things Are", daytaught: "Wednesday" },
{ id: "112", playlist: "2 Pairs & A Good Time", daytaught: "Wednesday" },
{ id: "111", playlist: "Like a Lasso", daytaught: "Wednesday" },
{ id: "110", playlist: "Need a Favor", daytaught: "Wednesday" },
{ id: "109", playlist: "Not at this Party", daytaught: "Wednesday" },
{ id: "108", playlist: "Lets Do Da Dance", daytaught: "Wednesday" },
{ id: "107", playlist: "Rowdy Crowd", daytaught: "Wednesday" },
{ id: "106", playlist: "Hoedown", daytaught: "Wednesday" },
{ id: "105", playlist: "Bar Cha Cha", daytaught: "Wednesday" },
{ id: "104", playlist: "The Cowboi Boogie", daytaught: "Wednesday" },
{ id: "103", playlist: "Bottle Rockets", daytaught: "Wednesday" },
{ id: "102", playlist: "Crankin Country", daytaught: "Wednesday" },
{ id: "101", playlist: "Hole in my Heart", daytaught: "Wednesday" },
{ id: "100", playlist: "Tip it Back", daytaught: "Wednesday" },
{ id: "99", playlist: " Footloose Cowgirl", daytaught: "Wednesday" },
{ id: "98", playlist: "Boots On The Ground", daytaught: "Wednesday" },
{ id: "97", playlist: "Cowgirls On", daytaught: "Wednesday" },
{ id: "96", playlist: "Dizzy", daytaught: "Wednesday" },
{ id: "95", playlist: "Just Sayin", daytaught: "Wednesday" },
{ id: "94", playlist: "Honky Tonkin About", daytaught: "Wednesday" },
{ id: "93", playlist: "Keeping Up(Bum Me a Smoke)", daytaught: "Wednesday" },
{ id: "92", playlist: "Boots on Bars", daytaught: "Wednesday" },
{ id: "91", playlist: "Up the Creek", daytaught: "Wednesday" },
{ id: "90", playlist: "4 Wheel High", daytaught: "Wednesday" },
{ id: "89", playlist: "Hang Tight", daytaught: "Wednesday" },
{ id: "88", playlist: "Four Wheel Drive-no teach OR Demo", daytaught: "Wednesday" },
{ id: "87", playlist: "Texas Girls", daytaught: "Wednesday" },
{ id: "86", playlist: "Made in Mexico", daytaught: "Wednesday" },
{ id: "85", playlist: "Wild Cards", daytaught: "Wednesday" },
{ id: "84", playlist: "I Got a Problem", daytaught: "Wednesday" },
{ id: "83", playlist: "No Hard Feelings", daytaught: "Wednesday" },
{ id: "82", playlist: "A Hole in the Bottle", daytaught: "Wednesday" },
{ id: "81", playlist: "Thicc as Thieves", daytaught: "Wednesday" },
{ id: "80", playlist: "Long Road to Richmond", daytaught: "Wednesday" },
{ id: "79", playlist: "But I Got A Beer In My Hand", daytaught: "Wednesday" },
{ id: "78", playlist: "Young Love", daytaught: "Wednesday" },
{ id: "77", playlist: "Whiskey or Wine?", daytaught: "Wednesday" },
{ id: "76", playlist: "Everything I Love", daytaught: "Wednesday" },
{ id: "75", playlist: "Hide and Seek", daytaught: "Wednesday" },
{ id: "74", playlist: "Lonely Drum", daytaught: "Wednesday" },
{ id: "73", playlist: "Blame's on You", daytaught: "Wednesday" },
{ id: "72", playlist: "No Can Do", daytaught: "Wednesday" },
{ id: "71", playlist: "AA ", daytaught: "Wednesday" },
{ id: "69", playlist: "Dancin' In The Country", daytaught: "Wednesday" },
{ id: "68", playlist: "Honky Tonkin' About", daytaught: "Wednesday" },
{ id: "67", playlist: "Mamma Maria", daytaught: "Wednesday" },
{ id: "66", playlist: "Boots Don't", daytaught: "Wednesday" },
{ id: "65", playlist: "Heartache On The Dance Floor", daytaught: "Wednesday" },
{ id: "64", playlist: "American Kids", daytaught: "Wednesday" },
{ id: "63", playlist: "Lay Low", daytaught: "Wednesday" },
{ id: "62", playlist: "Wrong Side of Truck Bed", daytaught: "Wednesday" },
{ id: "61", playlist: "Honky Tonk Hardwood Floors", daytaught: "Wednesday" },
{ id: "60", playlist: "Turn Up the Night(Miles On it)", daytaught: "Wednesday" },
{ id: "59", playlist: "Back Then Right Now", daytaught: "Wednesday" },
{ id: "58", playlist: "After Party(LoverLover)", daytaught: "Wednesday" },
{ id: "57", playlist: "Need Something You Proof", daytaught: "Wednesday" },
{ id: "56", playlist: "A Bar Song", daytaught: "Wednesday" },
{ id: "55", playlist: "Southbound", daytaught: "Wednesday" },
{ id: "54", playlist: "Sounds Like the Radio", daytaught: "Wednesday" },
{ id: "53", playlist: "Swangin", daytaught: "Wednesday" },
{ id: "52", playlist: "Little Less traveled", daytaught: "Wednesday" },
{ id: "51", playlist: "I gotta have it", daytaught: "Wednesday" },
{ id: "50", playlist: "Drive", daytaught: "Wednesday" },
{ id: "49", playlist: "Washed up in Austin", daytaught: "Wednesday" },
{ id: "48", playlist: "Nothing but you (Yeah You)", daytaught: "Wednesday" },
{ id: "47", playlist: "Miss Me More", daytaught: "Wednesday" },
{ id: "46", playlist: "Praise the Lord", daytaught: "Wednesday" },
{ id: "45", playlist: "Corn", daytaught: "Wednesday" },
{ id: "44", playlist: "Might as well be me", daytaught: "Wednesday" },
{ id: "43", playlist: "No body but yours", daytaught: "Wednesday" },
{ id: "42", playlist: "Good Time", daytaught: "Wednesday" },
{ id: "41", playlist: "Brand New Man", daytaught: "Wednesday" },
{ id: "40", playlist: "Bar None", daytaught: "Wednesday" },
{ id: "39", playlist: "Getting Good", daytaught: "Wednesday" },
{ id: "38", playlist: "Fancy Like", daytaught: "Wednesday" },
{ id: "37", playlist: "Where Cowboys are King", daytaught: "Wednesday" },
{ id: "36", playlist: "South of Queens(Hillbilly Bone)", daytaught: "Wednesday" },
{ id: "35", playlist: "Baytown Twang", daytaught: "Wednesday" },
{ id: "34", playlist: "Gives me shivers", daytaught: "Wednesday" },
{ id: "33", playlist: "Shake Shakin", daytaught: "Wednesday" },
{ id: "32", playlist: "Like I Love Country Music", daytaught: "Wednesday" },
{ id: "31", playlist: "Blame it on the Wine", daytaught: "Wednesday" },
{ id: "30", playlist: "23", daytaught: "Wednesday" },
{ id: "29", playlist: "Feels Like Gold", daytaught: "Wednesday" },
{ id: "28", playlist: "WCF(need this)", daytaught: "Wednesday" },
{ id: "27", playlist: "These old boots", daytaught: "Wednesday" },
{ id: "26", playlist: "Same Boat", daytaught: "Wednesday" },
{ id: "25", playlist: "In Love With lovin u", daytaught: "Wednesday" },
{ id: "24", playlist: "This is God's Country", daytaught: "Wednesday" },
{ id: "23", playlist: "Hard to Forget", daytaught: "Wednesday" },
{ id: "22", playlist: "She had me at Heads Carolina", daytaught: "Wednesday" },
{ id: "21", playlist: "Texas Time", daytaught: "Wednesday" },
{ id: "20", playlist: "Get Ready to Ride", daytaught: "Wednesday" },
{ id: "19", playlist: "I Need My Whiskey Glasses ", daytaught: "Wednesday" },
{ id: "18", playlist: "I'm glad you exist", daytaught: "Wednesday" },
{ id: "17", playlist: "Ready for It (This is it)", daytaught: "Wednesday" },
{ id: "16", playlist: "Mamma Maria", daytaught: "Wednesday" },
{ id: "15", playlist: "Canadian Stomp", daytaught: "Wednesday" },
{ id: "14", playlist: "Ride Em Cowboy", daytaught: "Wednesday" },
{ id: "13", playlist: "FootLoose", daytaught: "Wednesday" },
{ id: "12", playlist: "Redneck Angel", daytaught: "Wednesday" },
{ id: "11", playlist: "But it could buy me a boat-no teach OR demo", daytaught: "Wednesday" },
{ id: "10", playlist: "Rockin the Wagon Wheel", daytaught: "Wednesday" },
{ id: "9", playlist: "Chill Factor", daytaught: "Wednesday" },
{ id: "7", playlist: "I Got a Woman", daytaught: "Wednesday" },
{ id: "5", playlist: "Crank it up!", daytaught: "Wednesday" },
{ id: "2", playlist: "Shotgun Jenny", daytaught: "Wednesday" }
];

export { venueDanceMap };



