const venueDanceMap = [
{ id: 144, playlist: "High Beginner", daytaught: "Been By Now" },
{ id: 143, playlist: "Beginner", daytaught: "Capital H" },
{ id: 142, playlist: "Improver", daytaught: "Walk on the Beach" },
{ id: 141, playlist: "Improver", daytaught: "A Rattlesnake Kiss" },
{ id: 140, playlist: "High Beginner", daytaught: "Boots Off" },
{ id: 139, playlist: "High Beginner", daytaught: "Backup Plan" },
{ id: 138, playlist: "Beginner", daytaught: "Dance With You" },
{ id: 137, playlist: "High Beginner", daytaught: "Heart of Stone" },
{ id: 136, playlist: "High Beginner", daytaught: "Blame Texas" },
{ id: 135, playlist: "High Beginner", daytaught: "Wish you Well" },
{ id: 134, playlist: "Beginner", daytaught: "Single Again" },
{ id: 133, playlist: "Beginner", daytaught: "Something Bout the Summer" },
{ id: 132, playlist: "Beginner", daytaught: "A Country Song Came On" },
{ id: 131, playlist: "High Beginner", daytaught: "Weren t for the Wind" },
{ id: 130, playlist: "Intermediate", daytaught: "After Party" },
{ id: 129, playlist: "Improver", daytaught: "Brown Eyed 5 5" },
{ id: 128, playlist: "Beginner", daytaught: "Like It Like That" },
{ id: 127, playlist: "Absolute Beginner", daytaught: "Alligator Smile" },
{ id: 126, playlist: "Beginner", daytaught: "Choosin Texas" },
{ id: 125, playlist: "High Beginner", daytaught: "Do Si Dough" },
{ id: 124, playlist: "Beginner", daytaught: "Country Tightrope" },
{ id: 123, playlist: "Beginner", daytaught: "Getaway Car" },
{ id: 122, playlist: "High Beginner", daytaught: "Good Times and Tan Lines" },
{ id: 121, playlist: "Beginner", daytaught: "Dolly Would" },
{ id: 120, playlist: "High Beginner", daytaught: "Old Ropers" },
{ id: 119, playlist: "Absolute Beginner", daytaught: "Twenty Two" },
{ id: 118, playlist: "Easy Intermediate", daytaught: "Memory Lane-No Teach" },
{ id: 117, playlist: "Improver", daytaught: "Happen to Me" },
{ id: 116, playlist: "Beginner", daytaught: "Baby I Wanna Know" },
{ id: 115, playlist: "Improver", daytaught: "Two of Us(no teach/demo)" },
{ id: 114, playlist: "Improver", daytaught: "Gin & Tonic Kisses" },
{ id: 113, playlist: "High Beginner", daytaught: "Where the Wild Things Are" },
{ id: 112, playlist: "High Beginner", daytaught: "2 Pairs & A Good Time" },
{ id: 111, playlist: "High Beginner", daytaught: "Like a Lasso" },
{ id: 110, playlist: "Easy Improver", daytaught: "Need a Favor" },
{ id: 109, playlist: "Beginner", daytaught: "Not at this Party" },
{ id: 108, playlist: "Improver", daytaught: "Lets Do Da Dance" },
{ id: 107, playlist: "Absolute Beginner", daytaught: "Rowdy Crowd" },
{ id: 106, playlist: "Absolute Beginner", daytaught: "Hoedown" },
{ id: 105, playlist: "Beginner", daytaught: "Bar Cha Cha" },
{ id: 104, playlist: "Beginner", daytaught: "The Cowboi Boogie" },
{ id: 103, playlist: "Beginner", daytaught: "Bottle Rockets" },
{ id: 102, playlist: "High Beginner", daytaught: "Crankin Country" },
{ id: 101, playlist: "Improver", daytaught: "Hole in my Heart" },
{ id: 100, playlist: "Beginner", daytaught: "Tip it Back" },
{ id: 99, playlist: "Beginner", daytaught: " Footloose Cowgirl" },
{ id: 98, playlist: "Beginner", daytaught: "Boots On The Ground" },
{ id: 97, playlist: "Beginner", daytaught: "Cowgirls On" },
{ id: 96, playlist: "Intermediate", daytaught: "Dizzy" },
{ id: 95, playlist: "Beginner", daytaught: "Just Sayin" },
{ id: 94, playlist: "Easy Intermediate", daytaught: "Honky Tonkin About" },
{ id: 93, playlist: "High Improver", daytaught: "Keeping Up(Bum Me a Smoke)" },
{ id: 92, playlist: "High Beginner", daytaught: "Boots on Bars" },
{ id: 91, playlist: "Improver", daytaught: "Up the Creek" },
{ id: 90, playlist: "Intermediate", daytaught: "4 Wheel High" },
{ id: 89, playlist: "Improver", daytaught: "Hang Tight" },
{ id: 88, playlist: "Improver", daytaught: "Four Wheel Drive-no teach OR Demo" },
{ id: 87, playlist: "Easy Intermediate", daytaught: "Texas Girls" },
{ id: 86, playlist: "Beginner", daytaught: "Made in Mexico" },
{ id: 85, playlist: "Improver", daytaught: "Wild Cards" },
{ id: 84, playlist: "Improver", daytaught: "I Got a Problem" },
{ id: 83, playlist: "Improver", daytaught: "No Hard Feelings" },
{ id: 82, playlist: "High Improver", daytaught: "A Hole in the Bottle" },
{ id: 81, playlist: "Improver", daytaught: "Thicc as Thieves" },
{ id: 80, playlist: "Improver", daytaught: "Long Road to Richmond" },
{ id: 79, playlist: "High Beginner", daytaught: "But I Got A Beer In My Hand" },
{ id: 78, playlist: "Improver", daytaught: "Young Love" },
{ id: 77, playlist: "Easy Intermediate", daytaught: "Whiskey or Wine?" },
{ id: 76, playlist: "Intermediate", daytaught: "Everything I Love" },
{ id: 75, playlist: "Intermediate", daytaught: "Hide and Seek" },
{ id: 74, playlist: "Improver", daytaught: "Lonely Drum" },
{ id: 73, playlist: "High Improver", daytaught: "Blame's on You" },
{ id: 72, playlist: "Improver", daytaught: "No Can Do" },
{ id: 71, playlist: "Beginner", daytaught: "AA " },
{ id: 69, playlist: "Improver", daytaught: "Dancin' In The Country" },
{ id: 68, playlist: "Easy Intermediate", daytaught: "Honky Tonkin' About" },
{ id: 67, playlist: "Absolute Beginner", daytaught: "Mamma Maria" },
{ id: 66, playlist: "High Beginner", daytaught: "Boots Don't" },
{ id: 65, playlist: "Improver", daytaught: "Heartache On The Dance Floor" },
{ id: 64, playlist: "High Beginner", daytaught: "American Kids" },
{ id: 63, playlist: "Improver", daytaught: "Lay Low" },
{ id: 62, playlist: "High Beginner", daytaught: "Wrong Side of Truck Bed" },
{ id: 61, playlist: "High Improver", daytaught: "Honky Tonk Hardwood Floors" },
{ id: 60, playlist: "Improver", daytaught: "Turn Up the Night(Miles On it)" },
{ id: 59, playlist: "Improver", daytaught: "Back Then Right Now" },
{ id: 58, playlist: "Intermediate", daytaught: "After Party(LoverLover)" },
{ id: 57, playlist: "Beginner", daytaught: "Need Something You Proof" },
{ id: 56, playlist: "Beginner", daytaught: "A Bar Song" },
{ id: 55, playlist: "Improver", daytaught: "Southbound" },
{ id: 54, playlist: "Improver", daytaught: "Sounds Like the Radio" },
{ id: 53, playlist: "Beginner", daytaught: "Swangin" },
{ id: 52, playlist: "Beginner", daytaught: "Little Less traveled" },
{ id: 51, playlist: "Beginner", daytaught: "I gotta have it" },
{ id: 50, playlist: "Intermediate", daytaught: "Drive" },
{ id: 49, playlist: "High Improver", daytaught: "Washed up in Austin" },
{ id: 48, playlist: "Beginner", daytaught: "Nothing but you (Yeah You)" },
{ id: 47, playlist: "Improver", daytaught: "Miss Me More" },
{ id: 46, playlist: "Improver", daytaught: "Praise the Lord" },
{ id: 45, playlist: "Improver", daytaught: "Corn" },
{ id: 44, playlist: "Improver", daytaught: "Might as well be me" },
{ id: 43, playlist: "Improver", daytaught: "No body but yours" },
{ id: 42, playlist: "Improver", daytaught: "Good Time" },
{ id: 41, playlist: "Beginner", daytaught: "Brand New Man" },
{ id: 40, playlist: "Improver", daytaught: "Bar None" },
{ id: 39, playlist: "High Beginner", daytaught: "Getting Good" },
{ id: 38, playlist: "Beginner", daytaught: "Fancy Like" },
{ id: 37, playlist: "Beginner", daytaught: "Where Cowboys are King" },
{ id: 36, playlist: "Beginner", daytaught: "South of Queens(Hillbilly Bone)" },
{ id: 35, playlist: "High Beginner", daytaught: "Baytown Twang" },
{ id: 34, playlist: "Improver", daytaught: "Gives me shivers" },
{ id: 33, playlist: "High Improver", daytaught: "Shake Shakin" },
{ id: 32, playlist: "Beginner", daytaught: "Like I Love Country Music" },
{ id: 31, playlist: "Improver", daytaught: "Blame it on the Wine" },
{ id: 30, playlist: "Improver", daytaught: "23" },
{ id: 29, playlist: "Beginner", daytaught: "Feels Like Gold" },
{ id: 28, playlist: "Beginner", daytaught: "WCF(need this)" },
{ id: 27, playlist: "Beginner", daytaught: "These old boots" },
{ id: 26, playlist: "Improver", daytaught: "Same Boat" },
{ id: 25, playlist: "Improver", daytaught: "In Love With lovin u" },
{ id: 24, playlist: "Improver", daytaught: "This is God's Country" },
{ id: 23, playlist: "Beginner", daytaught: "Hard to Forget" },
{ id: 22, playlist: "Intermediate", daytaught: "She had me at Heads Carolina" },
{ id: 21, playlist: "Beginner", daytaught: "Texas Time" },
{ id: 20, playlist: "Easy Intermediate", daytaught: "Get Ready to Ride" },
{ id: 19, playlist: "Absolute Beginner", daytaught: "I Need My Whiskey Glasses " },
{ id: 18, playlist: "Beginner", daytaught: "I'm glad you exist" },
{ id: 17, playlist: "Improver", daytaught: "Ready for It (This is it)" },
{ id: 16, playlist: "Absolute Beginner", daytaught: "Mamma Maria" },
{ id: 15, playlist: "Beginner", daytaught: "Canadian Stomp" },
{ id: 14, playlist: "Improver", daytaught: "Ride Em Cowboy" },
{ id: 13, playlist: "Improver", daytaught: "FootLoose" },
{ id: 12, playlist: "High Beginner", daytaught: "Redneck Angel" },
{ id: 11, playlist: "Beginner", daytaught: "But it could buy me a boat-no teach OR demo" },
{ id: 10, playlist: "Beginner", daytaught: "Rockin the Wagon Wheel" },
{ id: 9, playlist: "Intermediate", daytaught: "Chill Factor" },
{ id: 7, playlist: "Beginner", daytaught: "I Got a Woman" },
{ id: 5, playlist: "Easy Intermediate", daytaught: "Crank it up!" },
{ id: 2, playlist: "Beginner", daytaught: "Shotgun Jenny" },

];

export { venueDanceMap };



